---
name: Publish to PYPI or TestPYPI
on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
permissions:
  contents: read
jobs:
  # Call the CI workflow to ensure all tests pass
  ci:
    uses: ./.github/workflows/python-ci.yaml
    permissions:
      contents: read
  publish-testpypi:
    name: Publish to Test PyPI
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: testpypi
      url: https://test.pypi.org/p/acme-linode-objectstorage
    permissions:
      id-token: write # Required for trusted publishing
    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    environment:
      name: pypi
      url: https://pypi.org/p/acme-linode-objectstorage
    permissions:
      id-token: write # Required for trusted publishing
    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish-pypi
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write # Required to create releases
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
          draft: false
          prerelease: false
